# TODO: Translation updated at 2024-07-02 20:33

translate english strings:

    # game/system/modules/setting_gpt.rpy:5
    old "Использовать ли нейросети при генерации диалогов"
    new "Whether to use neural networks when generating dialogues"

    # game/system/modules/setting_gpt.rpy:6
    old "с рандомизированными НПС?"
    new "with RNPCs"

    # game/system/modules/setting_gpt.rpy:8
    old "При включенной функции генерации нейросетями, реплики и ответы"
    new "With the neural network generation function enabled, replicas and responses"

    # game/system/modules/setting_gpt.rpy:9
    old "могут и будут генерироваться с помощью нейросетей, учитывая характер РНПС, их"
    new "they can and will be generated using neural networks, given the nature of RNPS, their"

    # game/system/modules/setting_gpt.rpy:10
    old "статистику влияния, ваши отношения и другие игровые моменты."
    new "influence statistics, your relationships, and other game highlights."

    # game/system/modules/setting_gpt.rpy:11
    old "Кроме того, генерируются слоганы для клубов внутри академии."
    new "In addition, slogans are generated for clubs within the academy."

    # game/system/modules/setting_gpt.rpy:12
    old "Ответы, генерируемые РНПС с помощью нейросети, могут иногда казаться глупыми и неуместными."
    new "The answers generated by RNPS using a neural network can sometimes seem silly and inappropriate."

    # game/system/modules/setting_gpt.rpy:13
    old "При заходе в меню взаимодействия с РНПС само меню может подлагать на пару секунд."
    new "When entering the NPC interaction menu, the menu itself can be delayed for a couple of seconds."

    # game/system/modules/setting_gpt.rpy:14
    old "Возможность может не работать на устройствах андроид. Все случаи индивидуальны и все зависит конкретно от устройства."
    new "The feature may not work on android devices. All cases are individual and everything depends specifically on the device."

    # game/system/modules/setting_gpt.rpy:26
    old "Не использовать"
    new "Do not use"

    # game/system/modules/setting_gpt.rpy:27
    old "Использовать"
    new "Use it"
